CC = g++
CFLAGS = -Wall -Wextra -g -std=c++11

all: q11 q12 q13

q11: q11.cpp
	$(CC) $(CFLAGS) -o q11 q11.cpp

q12: q12.cpp
	$(CC) $(CFLAGS) -o q12 q12.cpp

q13: q13.cpp
	$(CC) $(CFLAGS) -o q13 q13.cpp

clean:
	rm -f q11 q12 q13