CXX = g++
CXXFLAGS = -Wall -Wextra -O2

all: add2PB findPhone

add2PB: add2PB.cpp
	$(CXX) $(CXXFLAGS) -o add2PB add2PB.cpp

findPhone: findPhone.cpp
	$(CXX) $(CXXFLAGS) -o findPhone findPhone.cpp

clean:
	rm -f add2PB findPhone
